CREATE TABLE log.LOG (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	DATE_TIME DATETIME NOT NULL,
	IP varchar(15) NOT NULL,
	REQUEST varchar(100) NOT NULL,
	STATUS INTEGER NOT NULL,
	USER_AGENT varchar(255) NOT NULL,
	CONSTRAINT LOG_PK PRIMARY KEY (ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_general_ci ;
